# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Jakob Schöpe'

# Site footer
footer:
  copyright:
    notice: '© {year} Jakob Schöpe. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false
  show_powered_by: false

# Localization
locale:
  date_format: 'January 2, 2006'
  time_format: '03:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: true
